[package]
name = "palletefy"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"

[profile.release-debug]
inherits = "release"
debug = true

[dependencies]
argparse = "0.2.2"
fastrand = "1.9.0"
image = "0.24.6"
